### ISSUE TITLE
BOINC 7.17.0 fails to build on ubuntu-server 20.04.1 LTS

### ISSUE THREAD

**Issue by ivr588** [BOINC/boinc#3949]
**Describe the bug**
BOINC fails to build after a time with the following error:
hostinfo_unix.cpp:1615:20: note: ‘sprintf’ output 2 or more bytes (assuming 1025) into a destination of size 1024
 1615 |             sprintf(fullname, "%s/%s", tty_patterns[i].dir, devname);
      |             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CXXLD    boinc_client
/usr/bin/ld: boinc_client-async_file.o: undefined reference to symbol 'gzread'
/usr/bin/ld: /lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:783: boinc_client] Error 1
make[2]: Leaving directory '/home/david/tmp/client'
make[1]: *** [Makefile:646: all-recursive] Error 1
make[1]: Leaving directory '/home/david/tmp'
make: *** [Makefile:550: all] Error 2

**Steps To Reproduce**
1. cd ~/tmp
2. git clone https://github.com/BOINC/boinc.git .
3. ./_autosetup
4.  ./configure -C --disable-server
5. make

**Expected behavior**
expected a binary to be completely built

**Screenshots**
n/a

**System Information**
 - OS: ubuntu server 20.04.1 LTS 
 - BOINC Version: 7.17.0

**Additional context**
na

**Comment by AenBleidd** [comment]
Please check configure log for an issue related to libz

**Comment by adamradocz** [comment]
Did you install all the dependencies?
```
sudo apt-get update && sudo apt-get install -y --no-install-recommends \
    make m4 libtool autoconf automake gcc g++ pkg-config  openssl libcurl4 libcurl4-openssl-dev libssl-dev libnotify-dev
```

**Comment by AenBleidd** [comment]
Closed as a duplicate of #4010
