### PR TITLE
[lib] refactor crypt.cpp, set minimal required OpenSSL version to 3.0

### LINKED ISSUE #7185: boinc fails to build with OpenSSL 4.0
### Describe the bug

boinc fails to build against OpenSSL 4.0 due to additional use of `const` in OpenSSL 4.0

### Steps to reproduce

```
git clone https://github.com/BOINC/boinc.git
cd boinc/
./_autosetup
./configure --disable-static --disable-server
make
....
crypt.cpp:826:41: error: invalid conversion from 'const X509_NAME*' {aka 'const X509_name_st*'} to 'X509_NAME*' {aka 'X509_name_st*'} [-fpermissive]
  826 |             subj = X509_get_subject_name(cert);
      |                    ~~~~~~~~~~~~~~~~~~~~~^~~~~~
      |                                         |
      |                                         const X509_NAME* {aka const X509_name_st*}
```
Full log attached below.

### Expected behavior

boinc should build against OpenSSL 4.0.

### Screenshots

_No response_

### System information

Arch Linux Rolling
boinc HEAD https://github.com/BOINC/boinc/commit/3f4359fc344e4145c6ef71b840157a3c1c6bb2f2
OpenSSL 4.0.0

### Additional context

[boinc-openssl-4.0-build-failure.log](https://github.com/user-attachments/files/30280896/boinc-openssl-4.0-build-failure.log)

Adding the `const` would be a one line change:
```patch
--- a/lib/crypt.cpp
+++ b/lib/crypt.cpp
@@ -774,7 +774,7 @@ int cert_verify_file(
     DATA_BLOCK sig_db;
     BIO *bio;
     X509 *cert;
-    X509_NAME *subj;
+    const X509_NAME *subj;
 
     if (signatures->signatures.size() == 0) {
         printf("No signatures available for file ('%s').\n", origFile);
```
@felixonmars @pierres

### PR DESCRIPTION
**Pull request by AenBleidd**
## Summary by cubic
Refactors crypto to `OpenSSL` ≥ 3.0 and unifies key/signature APIs across client, scheduler, and tools. Old behavior used `OpenSSL` 1.x with mixed return semantics and inconsistent cert checks; new behavior uses `EVP`/`OSSL_PARAM`/`openssl/encoder`, returns explicit status + validity, and fixes certificate verification.

- Changes
  - Standardize returns:
    - `check_file_signature`/`check_string_signature` → `std::pair<int,bool>`.
    - `read_key_file` → `std::pair<int,R_RSA_*_KEY>`.
    - `generate_signature` → hex `std::string`.
    - `sign_executable` → `std::pair<int,std::string>`.
  - Remove `check_*_signature2`; remove `check_validity_of_cert` from public API; `cert_verify_file` now returns int status (0 = verified).
  - Enforce `OpenSSL` 3.0 in `m4/check_ssl.m4`, CMake (`find_package(OpenSSL 3.0)`), and CI; add `python3-openssl`, `pyopenssl`, `cryptography`.
  - Large refactor of `lib/crypt.cpp` and `lib/crypt_prog.cpp`; add `tests/unit-tests/lib/test_crypt.cpp`, `tests/sign_executable_tests.py`, and expand `tests/crypt_prog_tests.py`.

- Required migration
  - Replace `check_*_signature2` with `check_*_signature` and handle `std::pair<int,bool>` (check both status and validity).
  - Update callers of `read_key_file` and `sign_executable` to destructure `std::pair<int,...>`.
  - Treat `cert_verify_file` return 0 as success; update any boolean checks.
  - Consume `generate_signature` as a hex `std::string`.

<sup>Written for commit 024b9a2dd59c1845f766c8da20cf3e9d98a8a56f. Summary will update on new commits.</sup>

<a href="https://cubic.dev/pr/BOINC/boinc/pull/7209?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://www.cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://www.cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

### CODE REVIEW

File: lib/crypt.h [hunk 1]
```diff
@@ -18,128 +18,253 @@
...
+    unsigned char coefficient[MAX_RSA_PRIME_LEN];
 } R_RSA_PRIVATE_KEY;
 
 // functions to convert between OpenSSL's keys (using BIGNUMs)
 // and our binary format
 
-extern void openssl_to_keys(
-    RSA* rp, int nbits, R_RSA_PRIVATE_KEY& priv, R_RSA_PUBLIC_KEY& pub
+// function returns a tuple of values:
+// first 'int' value indicates and error code
```
Comment (Vulpine05) [inline lib/crypt.h]: Nitpick:  'and' should be 'an'.

File: lib/crypt.h [hunk 2]
```diff
@@ -18,128 +18,253 @@
...
+);
+// function returns a pair of values:
+// first 'bool' value indicates if the data was converted successfully
+// second 'unique_EVP_PKEY' is the public key
+// if the first value is false, the second value is either nullptr or invalid
+extern std::pair<bool, unique_EVP_PKEY> public_to_openssl(
+    const R_RSA_PUBLIC_KEY& pub
+);
+// function returns a pair of values:
+// first 'int' value indicates and error code
```
Comment (Vulpine05) [inline lib/crypt.h]: Nitpick: 'and' should be 'an'.

File: lib/crypt.h [hunk 3]
```diff
@@ -18,128 +18,253 @@
...
+// (0 - success, everything else - error)
+// second 'R_RSA_PUBLIC_KEY' value is the public key
+// converted from OpenSSL's EVP_PKEY
+// if the first value is not 0, the second value is invalid
+extern std::pair<int, R_RSA_PUBLIC_KEY> openssl_to_public(
+    const unique_EVP_PKEY& pkey
+);
+// function returns a pair of values:
+// first 'int' value indicates and error code
```
Comment (Vulpine05) [inline lib/crypt.h]: Nitpick: 'and' should be 'an'.

File: lib/crypt.h [hunk 4]
```diff
@@ -18,128 +18,253 @@
...
+// (true - success, false - failure)
+// second 'std::vector<uint8_t>' value is the block signature
+// if the first value is false, the second value is invalid
+extern std::pair<bool, std::vector<uint8_t>> sign_block(
+    const std::vector<uint8_t>& data, const R_RSA_PRIVATE_KEY& key
 );
-extern int check_file_signature(
-    const char* md5, R_RSA_PUBLIC_KEY&, DATA_BLOCK& signature, bool&
+// return a pair of values:
+// first 'int' value indicates and error code
```
Comment (Vulpine05) [inline lib/crypt.h]: Nitpick: 'and' should be 'an'.

File: lib/crypt.h [hunk 5]
```diff
@@ -18,128 +18,253 @@
...
+// (true - valid, false - invalid)
+extern std::pair<int, bool> check_file_signature(
+    const std::string& md5,
+    const R_RSA_PUBLIC_KEY& key,
+    const std::vector<uint8_t>& signature
 );
-extern int check_file_signature2(
-    const char* md5, const char* signature, const char* key, bool&
+// return a pair of values:
+// first 'int' value indicates and error code
```
Comment (Vulpine05) [inline lib/crypt.h]: Nitpick: 'and' should be 'an'.

File: lib/crypt.h [hunk 6]
```diff
@@ -18,128 +18,253 @@
...
+// (true - valid, false - invalid)
+extern std::pair<int, bool> check_file_signature(
+    const std::string& md5,
+    const std::string& signature,
+    const std::string& key
 );
-extern int check_string_signature(
-    const char* text, const char* signature, R_RSA_PUBLIC_KEY&, bool&
+// return a pair of values:
+// first 'int' value indicates and error code
```
Comment (Vulpine05) [inline lib/crypt.h]: Nitpick: 'and' should be 'an'.

File: lib/crypt.h [hunk 7]
```diff
@@ -18,128 +18,253 @@
...
+// (true - valid, false - invalid)
+extern std::pair<int, bool> check_string_signature(
+    const std::string& text,
+    const std::string& signature,
+    const R_RSA_PUBLIC_KEY& key
 );
-extern int check_string_signature2(
-    const char* text, const char* signature, const char* key, bool&
+// return a pair of values:
+// first 'int' value indicates and error code
```
Comment (Vulpine05) [inline lib/crypt.h]: Nitpick: 'and' should be 'an'.

File: lib/crypt.h [hunk 8]
```diff
@@ -18,128 +18,253 @@
...
-    char* text_to_sign, char* signature_hex, R_RSA_PRIVATE_KEY& key
+extern bool print_raw_data(FILE *f, const std::vector<uint8_t> &x);
+// return a pair of values:
+// first 'bool' value indicates if the data was read successfully
+// (true - success, false - failure)
+// second 'vector<uint8_t>' value is the data read from the file
+// if the first value is false, the second value is invalid
+extern std::pair<bool, std::vector<uint8_t>> scan_raw_data(FILE *f);
+// return a pair of values:
+// first 'int' value indicates and error code
```
Comment (Vulpine05) [inline lib/crypt.h]: Nitpick: 'and' should be 'an'.

**Review by Vulpine05 — COMMENTED** [review]
Minor grammar in comments, please review.

**Comment by AenBleidd** [comment]
@davidpanderson, please review.

**Comment by CharlieFenton** [comment]
@AenBleidd You have introduced 2 compiler warnings on the Mac. Please fix:
```
/Volumes/Dev/BOINC_GIT/boinc_trunk/lib/crypt.cpp:358:25: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
  358 |     return make_pair(0, move(pkey));
      |                         ^
      |                         std::
/Volumes/Dev/BOINC_GIT/boinc_trunk/lib/crypt.cpp:400:25: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
  400 |     return make_pair(0, move(pkey));
      |                         ^
      |                         std::

```
