### ISSUE TITLE
make_project error with crypt

### ISSUE THREAD

**Issue by krzyszp** [BOINC/boinc#1964]
Hi,
On Debian 9 stable make_project generates error:
```
Generating encryption keys
sh: 1: /home/boincadm/boinc/lib/crypt_prog: not found
FATAL ERROR: Command failed: /home/boincadm/boinc/lib/crypt_prog -genkey 1024 /home/boincadm/projects/gcctest/keys/upload_private /home/boincadm/projects/gcctest/keys/upload_public >/dev/null
```
Manually compiling by make crytp shows next error:

```
boincadm@Ryzen:~/boinc/lib$ make crypt
/usr/bin/g++ -g -O2 -Wall    crypt.cpp   -o crypt
crypt.cpp:23:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
<builtin>: recipe for target 'crypt' failed
make: *** [crypt] Error 1
```

**Comment by ChristianBeer** [comment]
The `Makefile` in `lib/` should build `crypt_prog` and include all required headers. Simply running `make crypt_prog` in `lib/` should work. I get lots of undefined references now. It looks like this is an issue with openssl 1.0 vs 1.1 and the API changes this brings with it. Which `libssl-dev` package do you have installed? I seem to have `libssl1.0-dev` which in theory should work but currently isn't.

**Comment by krzyszp** [comment]
make crypt_prog result:
`boincadm@Ryzen:~/boinc/lib$ make crypt_prog
  CXX      crypt_prog-crypt_prog.o
  CXXLD    libboinc_crypt.la
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
rm -f libboinc_crypt.a
/bin/ln .libs/libboinc_crypt.a .
  CXXLD    crypt_prog
crypt_prog-crypt_prog.o: In function `main':
/home/boincadm/boinc/lib/crypt_prog.cpp:129: undefined reference to `RSA_new'
/home/boincadm/boinc/lib/crypt_prog.cpp:154: undefined reference to `BN_new'
/home/boincadm/boinc/lib/crypt_prog.cpp:155: undefined reference to `BN_set_word'
/home/boincadm/boinc/lib/crypt_prog.cpp:159: undefined reference to `RSA_new'
/home/boincadm/boinc/lib/crypt_prog.cpp:160: undefined reference to `RSA_generate_key_ex'
/home/boincadm/boinc/lib/crypt_prog.cpp:164: undefined reference to `openssl_to_keys(rsa_st*, int, R_RSA_PRIVATE_KEY&, R_RSA_PUBLIC_KEY&)'
/home/boincadm/boinc/lib/crypt_prog.cpp:169: undefined reference to `print_key_hex(_IO_FILE*, KEY*, int)'
/home/boincadm/boinc/lib/crypt_prog.cpp:170: undefined reference to `print_key_hex(_IO_FILE*, KEY*, int)'
/home/boincadm/boinc/lib/crypt_prog.cpp:179: undefined reference to `scan_key_hex(_IO_FILE*, KEY*, int)'
/home/boincadm/boinc/lib/crypt_prog.cpp:183: undefined reference to `sign_file(char const*, R_RSA_PRIVATE_KEY&, DATA_BLOCK&)'
/home/boincadm/boinc/lib/crypt_prog.cpp:184: undefined reference to `print_hex_data(_IO_FILE*, DATA_BLOCK&)'
/home/boincadm/boinc/lib/crypt_prog.cpp:203: undefined reference to `scan_key_hex(_IO_FILE*, KEY*, int)'
/home/boincadm/boinc/lib/crypt_prog.cpp:209: undefined reference to `scan_hex_data(_IO_FILE*, DATA_BLOCK&)'
/home/boincadm/boinc/lib/crypt_prog.cpp:218: undefined reference to `check_file_signature(char const*, R_RSA_PUBLIC_KEY&, DATA_BLOCK&, bool&)'
/home/boincadm/boinc/lib/crypt_prog.cpp:192: undefined reference to `scan_key_hex(_IO_FILE*, KEY*, int)'
/home/boincadm/boinc/lib/crypt_prog.cpp:194: undefined reference to `generate_signature(char*, char*, R_RSA_PRIVATE_KEY&)'
/home/boincadm/boinc/lib/crypt_prog.cpp:233: undefined reference to `scan_key_hex(_IO_FILE*, KEY*, int)'
/home/boincadm/boinc/lib/crypt_prog.cpp:237: undefined reference to `scan_key_hex(_IO_FILE*, KEY*, int)'
/home/boincadm/boinc/lib/crypt_prog.cpp:243: undefined reference to `encrypt_private(R_RSA_PRIVATE_KEY&, DATA_BLOCK&, DATA_BLOCK&)'
/home/boincadm/boinc/lib/crypt_prog.cpp:246: undefined reference to `decrypt_public(R_RSA_PUBLIC_KEY&, DATA_BLOCK&, DATA_BLOCK&)'
/home/boincadm/boinc/lib/crypt_prog.cpp:256: undefined reference to `scan_hex_data(_IO_FILE*, DATA_BLOCK&)'
/home/boincadm/boinc/lib/crypt_prog.cpp:258: undefined reference to `check_validity(char const*, char const*, unsigned char*, char*)'
/home/boincadm/boinc/lib/crypt_prog.cpp:296: undefined reference to `scan_raw_data(_IO_FILE*, DATA_BLOCK&)'
/home/boincadm/boinc/lib/crypt_prog.cpp:300: undefined reference to `print_hex_data(_IO_FILE*, DATA_BLOCK&)'
/home/boincadm/boinc/lib/crypt_prog.cpp:322: undefined reference to `OPENSSL_init_crypto'
/home/boincadm/boinc/lib/crypt_prog.cpp:323: undefined reference to `OPENSSL_init_crypto'
/home/boincadm/boinc/lib/crypt_prog.cpp:324: undefined reference to `ENGINE_load_builtin_engines'
/home/boincadm/boinc/lib/crypt_prog.cpp:326: undefined reference to `BIO_new_fp'
/home/boincadm/boinc/lib/crypt_prog.cpp:332: undefined reference to `BIO_s_file'
/home/boincadm/boinc/lib/crypt_prog.cpp:332: undefined reference to `BIO_new'
/home/boincadm/boinc/lib/crypt_prog.cpp:333: undefined reference to `BIO_ctrl'
/home/boincadm/boinc/lib/crypt_prog.cpp:338: undefined reference to `RSA_new'
/home/boincadm/boinc/lib/crypt_prog.cpp:344: undefined reference to `scan_key_hex(_IO_FILE*, KEY*, int)'
/home/boincadm/boinc/lib/crypt_prog.cpp:348: undefined reference to `private_to_openssl(R_RSA_PRIVATE_KEY&, rsa_st*)'
/home/boincadm/boinc/lib/crypt_prog.cpp:362: undefined reference to `PEM_write_RSAPrivateKey'
/home/boincadm/boinc/lib/crypt_prog.cpp:285: undefined reference to `scan_hex_data(_IO_FILE*, DATA_BLOCK&)'
/home/boincadm/boinc/lib/crypt_prog.cpp:289: undefined reference to `print_raw_data(_IO_FILE*, DATA_BLOCK&)'
/home/boincadm/boinc/lib/crypt_prog.cpp:393: undefined reference to `RSA_new'
/home/boincadm/boinc/lib/crypt_prog.cpp:400: undefined reference to `PEM_read_RSAPrivateKey'
/home/boincadm/boinc/lib/crypt_prog.cpp:406: undefined reference to `openssl_to_private(rsa_st*, R_RSA_PRIVATE_KEY*)'
/home/boincadm/boinc/lib/crypt_prog.cpp:411: undefined reference to `print_key_hex(_IO_FILE*, KEY*, int)'
/home/boincadm/boinc/lib/crypt_prog.cpp:376: undefined reference to `scan_key_hex(_IO_FILE*, KEY*, int)'
/home/boincadm/boinc/lib/crypt_prog.cpp:383: undefined reference to `public_to_openssl(R_RSA_PUBLIC_KEY&, rsa_st*)'
/home/boincadm/boinc/lib/crypt_prog.cpp:384: undefined reference to `PEM_write_RSA_PUBKEY'
/home/boincadm/boinc/lib/crypt_prog.cpp:415: undefined reference to `PEM_read_RSA_PUBKEY'
/home/boincadm/boinc/lib/crypt_prog.cpp:421: undefined reference to `openssl_to_keys(rsa_st*, int, R_RSA_PRIVATE_KEY&, R_RSA_PUBLIC_KEY&)'
/home/boincadm/boinc/lib/crypt_prog.cpp:423: undefined reference to `public_to_openssl(R_RSA_PUBLIC_KEY&, rsa_st*)'
/home/boincadm/boinc/lib/crypt_prog.cpp:428: undefined reference to `print_key_hex(_IO_FILE*, KEY*, int)'
/home/boincadm/boinc/lib/crypt_prog.cpp:418: undefined reference to `ERR_print_errors'
/home/boincadm/boinc/lib/crypt_prog.cpp:403: undefined reference to `ERR_print_errors'
/home/boincadm/boinc/lib/crypt_prog.cpp:386: undefined reference to `ERR_print_errors'
collect2: error: ld returned 1 exit status
Makefile:1053: recipe for target 'crypt_prog' failed
make: *** [crypt_prog] Error 1
`

**Comment by ChristianBeer** [comment]
At first I saw this too but then I did:
```
make distclean
./_autosetup -f
./configure --disable-client --disable-manager --disable-fcgi
make
```
and `crypt_prog` was automatically built. This should also work for libssl-dev 1.1.0f-3. I don't dare to update right now but will setup a VM with a fresh Debian 9 to do some more testing.

P.S.: for multiline code you need to enclose it with three backticks on github. I edited your comments above so they are better readable.

**Comment by krzyszp** [comment]
Same error as in first post.

**Comment by ChristianBeer** [comment]
I thought this was fixed as I tested this with Debian Stretch rather extensively when they introduced libssl 1.1. I'l have a look at this over the weekend.

**Comment by ChristianBeer** [comment]
I installed a fresh Debian9 VM, cloned the code and build the server parts (including crypt_prog) without a problem. Could you do the same on your machine and clone into a new directory? It's possible that some leftover build artifacts from earlier builds with libssl 1.0 are interfering (`make distclean` is not reliable).

**Comment by krzyszp** [comment]
I just had create new VM and have exactly same problem as on physical machine.
Can you list me packages installed by you before cloning repository, please?
I have packages listed on official wiki (except, that PHP is in version 7) and additionally htop, mc and phpmyadmin.

**Comment by ChristianBeer** [comment]
I installed from the netinst CD and only selected default utilities and SSH server. I then manually installed the following packages (through aptitude):
```
automake
build-essential
default-libmysqlclient-dev
git
libssl-dev
libtool
libtool-bin
pkg-config
curl
libcurl4-openssl-dev
```
This allowed my to run: `./configure --disable-client --disable-manager && make` and I don't see build errors.
```
$ ldd lib/crypt_prog
        linux-vdso.so.1 (0x00007ffe653c5000)
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007ff34712c000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007ff346c99000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff346917000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff346613000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff3463fc000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff3461dd000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff345e3e000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff345c3a000)
        /lib64/ld-linux-x86-64.so.2 (0x000055732cb27000)
```

**Comment by krzyszp** [comment]
No, I haven't problems with make. The problem happens during make_project after make...

**Comment by ChristianBeer** [comment]
But your problem with `make_project` is that `lib/crypt_prog` is not found which should be there if `make` ran without errors. Can you check if after you run `make` there is a file `lib/crypt_prog` available?

**Comment by krzyszp** [comment]
No, isn't.
Also, trying to compile it shows errors from my second post.

**Comment by ChristianBeer** [comment]
That is strange. I can't reproduce your error in my stretch VM. I just rebuild BOINC from scratch and the libraries are correct and `crypt_prog` is created.
"Undefined reference" usually means that a library is missing to link the executable or the library does not contain the symbols needed. Let's try it that way. The symbols missing in your second post should be in `lib/libboinc_crypt.la`. Mine looks like this:
```
$ strings lib/libboinc_crypt.a |head -n 15
!<arch>
/               0           0     0     0       1214      `
Z_Z14print_hex_dataP8_IO_FILER10DATA_BLOCK
_Z15sprint_hex_dataPcR10DATA_BLOCK
_Z14print_raw_dataP8_IO_FILER10DATA_BLOCK
_Z13scan_raw_dataP8_IO_FILER10DATA_BLOCK
_Z13scan_hex_dataP8_IO_FILER10DATA_BLOCK
_Z13print_key_hexP8_IO_FILEP3KEYi
_Z12scan_key_hexP8_IO_FILEP3KEYi
_Z13sscan_key_hexPKcP3KEYi
_Z13read_key_filePKcR17R_RSA_PRIVATE_KEY
_Z15openssl_to_keysP6rsa_stiR17R_RSA_PRIVATE_KEYR16R_RSA_PUBLIC_KEY
_Z18private_to_opensslR17R_RSA_PRIVATE_KEYP6rsa_st
_Z15encrypt_privateR17R_RSA_PRIVATE_KEYR10DATA_BLOCKS2_
_Z9sign_filePKcR17R_RSA_PRIVATE_KEYR10DATA_BLOCK
```

Are you really sure that `make` is successful? For me it didn't even build the server parts before building `lib/crypt_prog`.

**Comment by krzyszp** [comment]
lib/libboinc_crypt.a doesn't exists on my machine.

**Comment by ChristianBeer** [comment]
Can you upload your `config.log` and your `make` output somewhere (e.g. https://pastebin.com/) so I can take a look at them? I guess that `configure` is silently complaining about something and doesn't create correct `Makefiles`.

**Comment by krzyszp** [comment]
config.log
https://pastebin.com/2pM1zewU
make log:
https://pastebin.com/qTFb0PiE

**Comment by ChristianBeer** [comment]
There it is:
```
======================================================================
WARNING: trying to build BOINC-server, but MYSQL was not be found.
If you dont want to build the server you should use --disable-server.
 
I am continuing now as if --disable-server had been specified.
 
======================================================================
```
I had to install `default-libmysqlclient-dev` in order to fix that. This will install `libmariadbclient-dev` which will make `configure` not complain about missing mysql headers.

**Comment by krzyszp** [comment]
Thank you!
It sort out the problem. My fault was using mariadb-server  package instead of default-libmysqlclient-dev.
As comment - mariadb default config is unsecure at some settings should by amended after installation.

**Comment by ChristianBeer** [comment]
I'm glad I could help. I'm opening a new issue for later to fix the mysql header detection and properly fail not silently turn of the server build.

**Comment by avt232** [comment]
Just a heads up here the equivalent packages required to sort out this cryptic issue on Amazon AMI (and I suppose CentOS/RedHat) are:

yum install mysql mysql-devel mysql-lib
