### ISSUE TITLE
boinc fails to build with OpenSSL 4.0

### ISSUE THREAD

**Issue by loqs** [BOINC/boinc#7185]
### Describe the bug

boinc fails to build against OpenSSL 4.0 due to additional use of `const` in OpenSSL 4.0

### Steps to reproduce

```
git clone https://github.com/BOINC/boinc.git
cd boinc/
./_autosetup
./configure --disable-static --disable-server
make
....
crypt.cpp:826:41: error: invalid conversion from 'const X509_NAME*' {aka 'const X509_name_st*'} to 'X509_NAME*' {aka 'X509_name_st*'} [-fpermissive]
  826 |             subj = X509_get_subject_name(cert);
      |                    ~~~~~~~~~~~~~~~~~~~~~^~~~~~
      |                                         |
      |                                         const X509_NAME* {aka const X509_name_st*}
```
Full log attached below.

### Expected behavior

boinc should build against OpenSSL 4.0.

### System information

Arch Linux Rolling
boinc HEAD https://github.com/BOINC/boinc/commit/3f4359fc344e4145c6ef71b840157a3c1c6bb2f2
OpenSSL 4.0.0

### Additional context

[boinc-openssl-4.0-build-failure.log](https://github.com/user-attachments/files/30280896/boinc-openssl-4.0-build-failure.log)

Adding the `const` would be a one line change:
```patch
--- a/lib/crypt.cpp
+++ b/lib/crypt.cpp
@@ -774,7 +774,7 @@ int cert_verify_file(
     DATA_BLOCK sig_db;
     BIO *bio;
     X509 *cert;
-    X509_NAME *subj;
+    const X509_NAME *subj;
 
     if (signatures->signatures.size() == 0) {
         printf("No signatures available for file ('%s').\n", origFile);
```
@felixonmars @pierres

**Comment by AenBleidd** [comment]
@loqs, thank you for the report.
I'm currently working on a complere refactor of this file, and I will fix this issue too.

**Comment by Vulpine05** [comment]
@AenBleidd, I have been working on a Google Test file for crypt.cpp.  it has been slow for me but I think I have a good set of tests.  I have not tried refactoring yet, I wanted a baseline.  I can submit the test cases as a PR if you want, but I have not done a final review for efficiency yet.

**Comment by AenBleidd** [comment]
No need: I have covered with tests and refactored almost all functions in crypt.cpp file.

**Comment by AenBleidd** [comment]
@Vulpine05, next time please let us know in advance if you're working on something.

**Comment by CharlieFenton** [comment]
I've upgraded to OpenSSL 4.0 in a local build for the Mac to test it, but haven't yet put it too a PR until I'm sure it doesn't cause any problems. I fixed that issue by changing lib/crypt.cpp line 777
from this
`    X509_NAME *subj;`
to this
`    const X509_NAME *subj;`

I did read in the OpenSSL change log that many X509 functions have been "constified" and code  using them will need to be adjusted accordingly, but i can't find that page right now. Note also that there is an OpenSSL 4.0.1 to address a number of vulnerabilities, but it has not yet been promoted to a stable release.

**Comment by AenBleidd** [comment]
@CharlieFenton, I think I will get rid of this function (and the corresponding pointer) completely since anyway this was deprecated since OpenSSL 3.0.

**Comment by rosset** [comment]
I'm using this patch to build 8.2.15 in Fedora rawhide w/ openssl4

https://src.fedoraproject.org/fork/filiperosset/rpms/boinc-client/blob/59a16a9f8edc30c962b3e43b76e82f07f26d7d5f/f/openssl4.patch

**Comment by AenBleidd** [comment]
@rosset, thank you for the patch.
However, as I already said, this will be fixed in a more clean way.

**Comment by LocutusOfBorg** [comment]
Hello, there still is a failure

crypt.cpp: In function 'int cert_verify_file(CERT_SIGS*, const std::string&, const std::string&)':
crypt.cpp:957:52: error: invalid conversion from 'const X509_NAME*' {aka 'const X509_name_st*'} to 'X509_NAME*' {aka 'X509_name_st*'} [-fpermissive]
  957 |             X509_NAME *subj = X509_get_subject_name(cert.get());
      |                               ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
      |                                                    |
      |                                                    const X509_NAME* {aka const X509_name_st*}
make[5]: *** [Makefile:1800: libboinc_crypt_la-crypt.lo] Error 1

**Comment by LocutusOfBorg** [comment]
Please check https://github.com/BOINC/boinc/pull/7253
