### ISSUE TITLE
[linux] Won't compile with glibc>=2.26 due to dropped xlocale.h

### ISSUE THREAD

**Issue by jonathonf** [BOINC/boinc#2183]
glibc=2.26 dropped `xlocale.h`, therefore this isn't available on Linux distros with this version (or newer) of glibc.

This has been seen and fixed in other projects, e.g. mesa [1] and Chez Scheme [2]. The fix may simply be ifdef'ing out the include as per https://github.com/cisco/ChezScheme/commit/b04e9123a427034a39fc9084ba2a8b04608bbb3b .

[1] https://bugs.freedesktop.org/show_bug.cgi?id=102454
[2] https://github.com/cisco/ChezScheme/issues/220

```
make[2]: Entering directory '/dev/shm/boinc/src/boinc/clientgui'
  CXX      boincmgr-AccountManagerInfoPage.o
  CXX      boincmgr-AccountInfoPage.o
  CXX      boincmgr-AccountManagerProcessingPage.o
  CXX      boincmgr-AccountManagerPropertiesPage.o
  CXX      boincmgr-AsyncRPC.o
  CXX      boincmgr-AdvancedFrame.o
  CXX      boincmgr-AlreadyExistsPage.o
  CXX      boincmgr-BOINCBaseView.o
  CXX      boincmgr-BOINCBaseFrame.o
AsyncRPC.cpp:23:10: fatal error: xlocale.h: No such file or directory
 #include <xlocale.h>
          ^~~~~~~~~~~
compilation terminated.
```

**Comment by AenBleidd** [comment]
I think this was fixed in d9e4691ebd1f8c6c9e66a54b7c24c19ce85b7b22
See pull request #2092

**Comment by jonathonf** [comment]
It's this one: https://github.com/BOINC/boinc/commit/e86f29e7fbc78faff6c9b9c8356ffe59049c116f

OK, I think that can be cherry-picked until there's a new BOINC release tagged. :)
