### PR TITLE
try to make python scripts work with python 3

### PR DESCRIPTION
**Pull request by davidpanderson**
Changes:
print()
except XXX as e (rather than except XXX: e)
from Boinc import XXX rather than import XXX
    (I'm not sure how it worked before)

This gets as far as importing the MySQLdb module, which doesn't work with python 3.
Need to use mysqlclient instead:
https://pypi.org/project/mysqlclient/

### CODE REVIEW

**Comment by davidpanderson** [comment]
Also need to check whether this works with python 2.7

**Comment by davidpanderson** [comment]
I got this mostly working but it looks like 2to3 does more or less the same thing.

**Comment by TheAspens** [comment]
Closing and re-opening to trigger re-run of automated tests.

Note - based on my local testing, the docker-server-build will fail on: 
" ---> Running in 4238793f3c29",
"\u001b[91mTraceback (most recent call last):",
"  File \"/boinc2docker/boinc2docker_create_app\", line 185, in <module>",
"\u001b[0m\u001b[91m    xmlmerge(src,join(args.projhome,f),idkey=k,mergeat=m)",
"  File \"/boinc2docker/boinc2docker_create_app\", line 164, in xmlmerge",
"\u001b[0m\u001b[91m    if dc.find(idkey).text==sc.find(idkey).text: break",
"AttributeError: 'NoneType' object has no attribute 'text'",
"\u001b[0m"]}

Which are steps that build boinc2docker which are not necessary for reviewing this pull request.  I'm going to look to see if the server tests can be setup to skip this setup.

**Comment by TheAspens** [comment]
I've opened a bug with @marius311 at https://github.com/marius311/boinc-server-docker/issues/57

**Comment by lfield** [comment]
Let’s leave this open until the tests pass, don’t want to get into bad habits. We have been waiting 5 months anyway.

**Comment by TheAspens** [comment]
Opening/closing again and this time it should pass the tests.

**Comment by TheAspens** [comment]
@lfield @davidpanderson - David mentioned in marius311/boinc-server-docker#57 that he didn't think this should be merged.  @davidpanderson can you update this pull request with your thoughts on this pull request?

**Comment by davidpanderson** [comment]
This PR isn't ready to merge AFAIK; there was an issue with the MySQL interface.  I'm not currently working on it.

**Comment by lfield** [comment]
@davidpanderson I tested this and it is fine from my perspective. I am happy to merge once the CI tests pass.

**Comment by TheAspens** [comment]
Just realized that I had to delete the cache's on travis to pick up my changes.  Now that I have done that I'm closing and re-opening this again to re-trigger the CI.

**Comment by TheAspens** [comment]
After a lot of testing the boinc-server-test logic, I tried to build this branch normally.  When I attempted to the tools/upgrade script it fails with this:
```
Don't forget to do 'make' first!
Overwrite files in /www/boinc[y/N] y
Traceback (most recent call last):
  File "./upgrade", line 70, in <module>
    if not tools.query_noyes("Overwrite files in "+INSTALL_DIR):
  File "/home/knreed/boinc/py/Boinc/tools.py", line 76, in query_noyes
    choice = input(question + "[y/N] ").lower()
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined
```
This is because it is invoking python and not python3.

Other than the testing I just did, has this been tested in creating a new project or updating an existing project?

**Comment by lfield** [comment]
I don't understand why this is failing. Locally it is working for me. I am using` boinc-server-test maser and made the following change. 
> -  shell: docker-compose build --no-cache
> +  shell: TAG="" docker-compose build --no-cache
Then I ran the following which was successful. 
`ansible-playbook -i hosts build.yml --extra-vars "boinc_repository=https://github.com/BOINC/boinc boinc_branch=dpa_python3"`

I also don't understand the [Travis error](https://travis-ci.org/BOINC/boinc/jobs/523551059).

**Comment by TheAspens** [comment]
I had to flush the caches on Travis to get it to build correctly.  It seemed to have an older version.  It now gets a 404 on the tests.

Also - I had to disable a test because without building boinc2docker there are no platforms loaded.  So fetch the latest boinc2docker before building locally.

**Comment by TheAspens** [comment]
Actually - it gets a 404 on this code below in the integration_test/installTestSuite.sh which is the test to wait for the server to finish starting up.  Since the project isn't getting built properly, this is 404 forever. 

```
until $(curl -o /dev/null -SsifL http://127.0.0.1/boincserver/index.php ); do
    printf '.'
    sleep 5
done

```

**Comment by TheAspens** [comment]
Anyway, it is now correctly showing that the project is not being installed/built in the docker container.

**Comment by lfield** [comment]
I have found the issue. The config.xml is not being generated correctly. The tasks and daemons elements are empty. Will fix it.

**Comment by lfield** [comment]
It seems that assignments such as [this one](https://github.com/BOINC/boinc/blob/master/tools/make_project#L249) have no effect. Any ideas before I dig deeper?

**Comment by lfield** [comment]
@davidpanderson it might be quicker for you to fix this as you are more familiar with it than I am. The issue is that the task and daemons in the config.xml are not defined.
```
    <tasks/>
    <daemons/>
```

**Comment by davidpanderson** [comment]
Does make_project, run with Python 3, create a database?
What MySQL interface module did you use?

**Comment by lfield** [comment]
Yes. I used boinc-server-test with this branch.

**Comment by lfield** [comment]
The issue is that this [map function](https://github.com/BOINC/boinc/blob/master/py/Boinc/boincxml.py#L99) does not work in Python 3. Does anyone care to comment before I turn it into a for loop so that it will work with python 2 and 3? You can test this with the following.

```
def sq(x):
    print(x*x)
x = [0,1,2]
map(sq, x)
```

**Comment by lfield** [comment]
This works now but the httpd.conf file was not linked.

**Comment by lfield** [comment]
The tests now pass I now have a conflict on interest with this PR. Please can someone else check and merge.

**Comment by lfield** [comment]
Spoke to soon. Still not working. Investigating ...

**Comment by lfield** [comment]
Now it is ready.

**Comment by TheAspens** [comment]
@lfield - tried to create a new project and got

```
Traceback (most recent call last):
  File "./make_project", line 7, in <module>
    from Boinc.setup_project import *
  File "/home/knreed/boinc/py/Boinc/setup_project.py", line 9, in <module>
    from Boinc import database, db_mid, configxml, tools
  File "/home/knreed/boinc/py/Boinc/database.py", line 33, in <module>
    from Boinc.db_base import *
  File "/home/knreed/boinc/py/Boinc/db_base.py", line 15, in <module>
    import MySQLdb, MySQLdb.cursors
```

and there is no MySQLdb library for python3.

Can you let me know what I'm missing?  FYI - I'm running on Red Hat 7. 

thanks,
Kevin

**Comment by TheAspens** [comment]
Ok the mysqlclient package from https://pypi.org/project/mysqlclient/ solved the issue.

I needed to run the following in order to get things installed on my existing python3 installation:
```
sudo yum install python36-pip mysql-devel python3-devel
sudo pip36 install mysqlclient
```
I'm continuing testing.

**Comment by TheAspens** [comment]
I was able to create a new project successfully so that is good.  I have more testing to do but I have a question about the following files:

- ./stripchart/samples/parse_config
- ./tools/parse_config
- ./tools/dbcheck_files_exist
- ./tools/check_project
- ./tools/appmgr
- ./sched/start

These are all python files as well that probably need to be updated to use python3 as well.  I tested switching sched/start to python3 and got the following error:

```
  File "bin/status", line 228
    except OSError, e:
                  ^

```

what are your thoughts about updating these as well?  I assume the goal is to run on a platform without python2 installed?

**Comment by lfield** [comment]
I don't know what the goal is but we should not attempt to support Python 3 in one go. As long as the commits are atomic, we can address it in stages.

**Comment by TheAspens** [comment]
This change is not backwards compatible.  As a result, if we merged this change in, then a server would require both python2 and python3 fully setup and configured in order to operate.  In my opinion, we would then have a blocker issue to remove any remaining dependencies on python2 before we created a new server release.

Also - the change from python2 -> python3 in my opinion would require a major version number revision (i.e. 2.0.0).

**Comment by lfield** [comment]
Having both Python 2 and 3 on the same system is fine.

**Comment by TheAspens** [comment]
I tested doing a server build from server_release 1.0.4 and then doing an upgrade to this release and got the following:

```
Traceback (most recent call last):
  File "./upgrade", line 81, in <module>
    install_boinc_files(INSTALL_DIR, not options.server_only, not options.web_only)
  File "/home/knreed/boinc/py/Boinc/setup_project.py", line 391, in install_boinc_files
    install(builddest('sched',f), dest('cgi-bin',f))
NameError: name 'builddest' is not defined
```

I'm looking into the issue.

Also note that I have created a server_release/1/1.1 branch that can be used as the last python2 release.  That will let us merge this into master as soon as it is ready.

**Comment by TheAspens** [comment]
I've tested both creating a new project and updating a project from server release 1.0.4 and both processes now work correctly.  I'm accepting this pull request.

Thanks @lfield and @davidpanderson  for this work!
