### ISSUE TITLE
Cannot build with OpenSSL 3.0

### ISSUE THREAD

**Issue by knuxify** [BOINC/boinc#4524]
**Describe the bug**
OpenSSL 3.0 has recently been released. Some distros may be switching to it soon - Alpine Linux has already upgraded its OpenSSL package on edge (although it offers backwards-compatiblity with OpenSSL 1.1 via the ``openssl1.1-compat`` package).

However, due to larger API changes, the build fails on the crypt.cpp file, as shown in the logs at the end of this bug report. There are also plenty of deprecation warnings, but these are less important.

**Steps To Reproduce**
1. Use OpenSSL 3.0 to build BOINC

**Expected behavior**
The build passes successfully.

**System Information**
 - OS: Alpine Linux Edge
 - BOINC Version: 7.16.19

**Additional context**

[Migration guide](https://www.openssl.org/docs/man3.0/man7/migration_guide.html)

The exact build error:
```
crypt.cpp:676:32: error: invalid conversion from 'const rsa_st*' to 'RSA*' {aka 'rsa_st*'} [-fpermissive]
  676 |         rsa = EVP_PKEY_get0_RSA(pubKey);
      |               ~~~~~~~~~~~~~~~~~^~~~~~~~
      |                                |
      |                                const rsa_st*

```

<details>
<summary>The failing portion of the build logs:</summary>

```
  CXX      libboinc_crypt_la-crypt.lo
crypt.cpp: In function 'int encrypt_private(R_RSA_PRIVATE_KEY&, DATA_BLOCK&, DATA_BLOCK&)':
crypt.cpp:265:23: warning: 'RSA* RSA_new()' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  265 |     RSA* rp = RSA_new();
      |                       ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:201:28: note: declared here
  201 | OSSL_DEPRECATEDIN_3_0 RSA *RSA_new(void);
      |                            ^~~~~~~
crypt.cpp:267:77: warning: 'int RSA_private_encrypt(int, const unsigned char*, unsigned char*, RSA*, int)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  267 |     retval = RSA_private_encrypt(n, in.data, out.data, rp, RSA_PKCS1_PADDING);
      |                                                                             ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:285:5: note: declared here
  285 | int RSA_private_encrypt(int flen, const unsigned char *from, unsigned char *to,
      |     ^~~~~~~~~~~~~~~~~~~
crypt.cpp:269:20: warning: 'void RSA_free(RSA*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  269 |         RSA_free(rp);
      |                    ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:293:28: note: declared here
  293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      |                            ^~~~~~~~
crypt.cpp:272:26: warning: 'int RSA_size(const RSA*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  272 |     out.len = RSA_size(rp);
      |                          ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:204:27: note: declared here
  204 | OSSL_DEPRECATEDIN_3_0 int RSA_size(const RSA *rsa);
      |                           ^~~~~~~~
crypt.cpp:273:16: warning: 'void RSA_free(RSA*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  273 |     RSA_free(rp);
      |                ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:293:28: note: declared here
  293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      |                            ^~~~~~~~
crypt.cpp: In function 'int decrypt_public(R_RSA_PUBLIC_KEY&, DATA_BLOCK&, DATA_BLOCK&)':
crypt.cpp:279:23: warning: 'RSA* RSA_new()' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  279 |     RSA* rp = RSA_new();
      |                       ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:201:28: note: declared here
  201 | OSSL_DEPRECATEDIN_3_0 RSA *RSA_new(void);
      |                            ^~~~~~~
crypt.cpp:281:81: warning: 'int RSA_public_decrypt(int, const unsigned char*, unsigned char*, RSA*, int)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  281 |     retval = RSA_public_decrypt(in.len, in.data, out.data, rp, RSA_PKCS1_PADDING);
      |                                                                                 ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:288:5: note: declared here
  288 | int RSA_public_decrypt(int flen, const unsigned char *from, unsigned char *to,
      |     ^~~~~~~~~~~~~~~~~~
crypt.cpp:283:20: warning: 'void RSA_free(RSA*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  283 |         RSA_free(rp);
      |                    ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:293:28: note: declared here
  293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      |                            ^~~~~~~~
crypt.cpp:286:26: warning: 'int RSA_size(const RSA*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  286 |     out.len = RSA_size(rp);
      |                          ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:204:27: note: declared here
  204 | OSSL_DEPRECATEDIN_3_0 int RSA_size(const RSA *rsa);
      |                           ^~~~~~~~
crypt.cpp:287:16: warning: 'void RSA_free(RSA*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  287 |     RSA_free(rp);
      |                ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:293:28: note: declared here
  293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      |                            ^~~~~~~~
crypt.cpp: In function 'void openssl_to_keys(RSA*, int, R_RSA_PRIVATE_KEY&, R_RSA_PUBLIC_KEY&)':
crypt.cpp:473:32: warning: 'void RSA_get0_key(const RSA*, const BIGNUM**, const BIGNUM**, const BIGNUM**)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  473 |     RSA_get0_key(rp, &n, &e, &d);
      |                                ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:217:28: note: declared here
  217 | OSSL_DEPRECATEDIN_3_0 void RSA_get0_key(const RSA *r,
      |                            ^~~~~~~~~~~~
crypt.cpp:474:32: warning: 'void RSA_get0_factors(const RSA*, const BIGNUM**, const BIGNUM**)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  474 |     RSA_get0_factors(rp, &p, &q);
      |                                ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:220:28: note: declared here
  220 | OSSL_DEPRECATEDIN_3_0 void RSA_get0_factors(const RSA *r,
      |                            ^~~~~~~~~~~~~~~~
crypt.cpp:475:48: warning: 'void RSA_get0_crt_params(const RSA*, const BIGNUM**, const BIGNUM**, const BIGNUM**)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  475 |     RSA_get0_crt_params(rp, &dmp1, &dmq1, &iqmp);
      |                                                ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:225:28: note: declared here
  225 | OSSL_DEPRECATEDIN_3_0 void RSA_get0_crt_params(const RSA *r,
      |                            ^~~~~~~~~~~~~~~~~~~
crypt.cpp: In function 'void private_to_openssl(R_RSA_PRIVATE_KEY&, RSA*)':
crypt.cpp:526:29: warning: 'int RSA_set0_key(RSA*, BIGNUM*, BIGNUM*, BIGNUM*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  526 |     RSA_set0_key(rp, n, e, d);
      |                             ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:207:27: note: declared here
  207 | OSSL_DEPRECATEDIN_3_0 int RSA_set0_key(RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d);
      |                           ^~~~~~~~~~~~
crypt.cpp:527:30: warning: 'int RSA_set0_factors(RSA*, BIGNUM*, BIGNUM*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  527 |     RSA_set0_factors(rp, p, q);
      |                              ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:208:27: note: declared here
  208 | OSSL_DEPRECATEDIN_3_0 int RSA_set0_factors(RSA *r, BIGNUM *p, BIGNUM *q);
      |                           ^~~~~~~~~~~~~~~~
crypt.cpp:528:45: warning: 'int RSA_set0_crt_params(RSA*, BIGNUM*, BIGNUM*, BIGNUM*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  528 |     RSA_set0_crt_params(rp, dmp1, dmq1, iqmp);
      |                                             ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:209:27: note: declared here
  209 | OSSL_DEPRECATEDIN_3_0 int RSA_set0_crt_params(RSA *r,
      |                           ^~~~~~~~~~~~~~~~~~~
crypt.cpp: In function 'void public_to_openssl(R_RSA_PUBLIC_KEY&, RSA*)':
crypt.cpp:547:32: warning: 'int RSA_set0_key(RSA*, BIGNUM*, BIGNUM*, BIGNUM*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  547 |     RSA_set0_key(rp, n, e, NULL);
      |                                ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:207:27: note: declared here
  207 | OSSL_DEPRECATEDIN_3_0 int RSA_set0_key(RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d);
      |                           ^~~~~~~~~~~~
crypt.cpp: In function 'int openssl_to_private(RSA*, R_RSA_PRIVATE_KEY*)':
crypt.cpp:577:34: warning: 'void RSA_get0_key(const RSA*, const BIGNUM**, const BIGNUM**, const BIGNUM**)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  577 |     RSA_get0_key(from, &n, &e, &d);
      |                                  ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:217:28: note: declared here
  217 | OSSL_DEPRECATEDIN_3_0 void RSA_get0_key(const RSA *r,
      |                            ^~~~~~~~~~~~
crypt.cpp:578:34: warning: 'void RSA_get0_factors(const RSA*, const BIGNUM**, const BIGNUM**)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  578 |     RSA_get0_factors(from, &p, &q);
      |                                  ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:220:28: note: declared here
  220 | OSSL_DEPRECATEDIN_3_0 void RSA_get0_factors(const RSA *r,
      |                            ^~~~~~~~~~~~~~~~
crypt.cpp:579:50: warning: 'void RSA_get0_crt_params(const RSA*, const BIGNUM**, const BIGNUM**, const BIGNUM**)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  579 |     RSA_get0_crt_params(from, &dmp1, &dmq1, &iqmp);
      |                                                  ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:225:28: note: declared here
  225 | OSSL_DEPRECATEDIN_3_0 void RSA_get0_crt_params(const RSA *r,
      |                            ^~~~~~~~~~~~~~~~~~~
crypt.cpp: In function 'int check_validity_of_cert(const char*, const unsigned char*, unsigned char*, int, const char*)':
crypt.cpp:676:39: warning: 'const rsa_st* EVP_PKEY_get0_RSA(const EVP_PKEY*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  676 |         rsa = EVP_PKEY_get0_RSA(pubKey);
      |                                       ^
In file included from /usr/include/openssl/x509.h:29,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/evp.h:1346:22: note: declared here
 1346 | const struct rsa_st *EVP_PKEY_get0_RSA(const EVP_PKEY *pkey);
      |                      ^~~~~~~~~~~~~~~~~
crypt.cpp:676:32: error: invalid conversion from 'const rsa_st*' to 'RSA*' {aka 'rsa_st*'} [-fpermissive]
  676 |         rsa = EVP_PKEY_get0_RSA(pubKey);
      |               ~~~~~~~~~~~~~~~~~^~~~~~~~
      |                                |
      |                                const rsa_st*
crypt.cpp:677:36: warning: 'int RSA_blinding_on(RSA*, BN_CTX*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  677 |         if (!RSA_blinding_on(rsa, c)) {
      |                                    ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:371:27: note: declared here
  371 | OSSL_DEPRECATEDIN_3_0 int RSA_blinding_on(RSA *rsa, BN_CTX *ctx);
      |                           ^~~~~~~~~~~~~~~
crypt.cpp:688:86: warning: 'int RSA_verify(int, const unsigned char*, unsigned int, const unsigned char*, unsigned int, RSA*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  688 |         retval = RSA_verify(NID_md5, md5_md, MD5_DIGEST_LENGTH, sfileMsg, sfsize, rsa);
      |                                                                                      ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:351:27: note: declared here
  351 | OSSL_DEPRECATEDIN_3_0 int RSA_verify(int type, const unsigned char *m,
      |                           ^~~~~~~~~~
crypt.cpp:689:29: warning: 'void RSA_blinding_off(RSA*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  689 |         RSA_blinding_off(rsa);
      |                             ^
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from crypt.cpp:36:
/usr/include/openssl/rsa.h:372:28: note: declared here
  372 | OSSL_DEPRECATEDIN_3_0 void RSA_blinding_off(RSA *rsa);
      |                            ^~~~~~~~~~~~~~~~
crypt.cpp: In function 'char* check_validity(const char*, const char*, unsigned char*, char*)':
crypt.cpp:729:21: warning: 'int MD5_Init(MD5_CTX*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  729 |     MD5_Init(&md5CTX);
      |                     ^
In file included from crypt.cpp:37:
/usr/include/openssl/md5.h:49:27: note: declared here
   49 | OSSL_DEPRECATEDIN_3_0 int MD5_Init(MD5_CTX *c);
      |                           ^~~~~~~~
crypt.cpp:731:41: warning: 'int MD5_Update(MD5_CTX*, const void*, size_t)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  731 |         MD5_Update(&md5CTX, rbuf, rbytes);
      |                                         ^
In file included from crypt.cpp:37:
/usr/include/openssl/md5.h:50:27: note: declared here
   50 | OSSL_DEPRECATEDIN_3_0 int MD5_Update(MD5_CTX *c, const void *data, size_t len);
      |                           ^~~~~~~~~~
crypt.cpp:733:30: warning: 'int MD5_Final(unsigned char*, MD5_CTX*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  733 |     MD5_Final(md5_md, &md5CTX);
      |                              ^
In file included from crypt.cpp:37:
/usr/include/openssl/md5.h:51:27: note: declared here
   51 | OSSL_DEPRECATEDIN_3_0 int MD5_Final(unsigned char *md, MD5_CTX *c);
      |                           ^~~~~~~~~
crypt.cpp: In function 'int cert_verify_file(CERT_SIGS*, const char*, const char*)':
crypt.cpp:777:21: warning: 'int MD5_Init(MD5_CTX*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  777 |     MD5_Init(&md5CTX);
      |                     ^
In file included from crypt.cpp:37:
/usr/include/openssl/md5.h:49:27: note: declared here
   49 | OSSL_DEPRECATEDIN_3_0 int MD5_Init(MD5_CTX *c);
      |                           ^~~~~~~~
crypt.cpp:779:41: warning: 'int MD5_Update(MD5_CTX*, const void*, size_t)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  779 |         MD5_Update(&md5CTX, rbuf, rbytes);
      |                                         ^
In file included from crypt.cpp:37:
/usr/include/openssl/md5.h:50:27: note: declared here
   50 | OSSL_DEPRECATEDIN_3_0 int MD5_Update(MD5_CTX *c, const void *data, size_t len);
      |                           ^~~~~~~~~~
crypt.cpp:781:30: warning: 'int MD5_Final(unsigned char*, MD5_CTX*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  781 |     MD5_Final(md5_md, &md5CTX);
      |                              ^
In file included from crypt.cpp:37:
/usr/include/openssl/md5.h:51:27: note: declared here
   51 | OSSL_DEPRECATEDIN_3_0 int MD5_Final(unsigned char *md, MD5_CTX *c);
      |                           ^~~~~~~~~
make[2]: *** [Makefile:1764: libboinc_crypt_la-crypt.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
gui_rpc_client_ops.cpp: In member function 'int RPC_CLIENT::run_graphics_app(const char*, int&, const char*)':
gui_rpc_client_ops.cpp:1978:10: warning: variable 'stop' set but not used [-Wunused-but-set-variable]
 1978 |     bool stop = false;
      |          ^~~~
make[2]: Leaving directory '/home/knuxify/aports/testing/boinc/src/boinc-client_release-7.16-7.16.19/lib'
make[1]: *** [Makefile:648: all-recursive] Error 1
make[1]: Leaving directory '/home/knuxify/aports/testing/boinc/src/boinc-client_release-7.16-7.16.19'
make: *** [Makefile:552: all] Error 2
```
</details>

**Comment by AenBleidd** [comment]
As soon as OpenSsl 1.1.1* is not deprecated yet, not sure we will switch to OpenSsl 3.0 soon, so I see no reason to fix all `deprecated` warnings. Also, since OpenSsl release is quite fresh and not properly tested, it's also dangerous to drop existing implementation support and switch immediately to new release
However, looking at the build log, it won't be a big deal to fix 1 build error.
@knuxify, if you can provide a patch that will fix this build error and keep backward compatibility with OpenSsl 1.1.1* - that would be really great.
Thanks in advance.

**Comment by AenBleidd** [comment]
vcpkg reference: https://github.com/microsoft/vcpkg/issues/20031

**Comment by barton2526** [comment]
Perhaps this should be changed to say "Build Windows with OpenSSL 1.1.1-

**Comment by AenBleidd** [comment]
Fixed via #4563
